//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StudentInfo")]
  public partial class StudentInfo : global::ProtoBuf.IExtensible
  {
    public StudentInfo() {}
    
    private string _apply_place = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"apply_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_place
    {
      get { return _apply_place; }
      set { _apply_place = value; }
    }
    private string _aplly_number = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"aplly_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string aplly_number
    {
      get { return _aplly_number; }
      set { _aplly_number = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _name_spell = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name_spell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_spell
    {
      get { return _name_spell; }
      set { _name_spell = value; }
    }
    private string _number = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string number
    {
      get { return _number; }
      set { _number = value; }
    }
    private string _card_type = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_type
    {
      get { return _card_type; }
      set { _card_type = value; }
    }
    private string _card_number = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"card_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string card_number
    {
      get { return _card_number; }
      set { _card_number = value; }
    }
    private string _birth = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"birth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string birth
    {
      get { return _birth; }
      set { _birth = value; }
    }
    private string _nation = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nation
    {
      get { return _nation; }
      set { _nation = value; }
    }
    private string _gender = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _marriage = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"marriage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string marriage
    {
      get { return _marriage; }
      set { _marriage = value; }
    }
    private string _soldier = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"soldier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string soldier
    {
      get { return _soldier; }
      set { _soldier = value; }
    }
    private string _politics_status = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"politics_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string politics_status
    {
      get { return _politics_status; }
      set { _politics_status = value; }
    }
    private string _native_place = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"native_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string native_place
    {
      get { return _native_place; }
      set { _native_place = value; }
    }
    private string _birth_place = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"birth_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string birth_place
    {
      get { return _birth_place; }
      set { _birth_place = value; }
    }
    private string _register_place = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"register_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string register_place
    {
      get { return _register_place; }
      set { _register_place = value; }
    }
    private string _register_address = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"register_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string register_address
    {
      get { return _register_address; }
      set { _register_address = value; }
    }
    private string _record_place = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"record_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string record_place
    {
      get { return _record_place; }
      set { _record_place = value; }
    }
    private string _record_ministry = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"record_ministry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string record_ministry
    {
      get { return _record_ministry; }
      set { _record_ministry = value; }
    }
    private string _record_address = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"record_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string record_address
    {
      get { return _record_address; }
      set { _record_address = value; }
    }
    private string _record_place_postcode = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"record_place_postcode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string record_place_postcode
    {
      get { return _record_place_postcode; }
      set { _record_place_postcode = value; }
    }
    private string _work_place = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"work_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string work_place
    {
      get { return _work_place; }
      set { _work_place = value; }
    }
    private string _work_experience = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"work_experience", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string work_experience
    {
      get { return _work_experience; }
      set { _work_experience = value; }
    }
    private string _reward_punishment = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"reward_punishment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reward_punishment
    {
      get { return _reward_punishment; }
      set { _reward_punishment = value; }
    }
    private string _family = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"family", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string family
    {
      get { return _family; }
      set { _family = value; }
    }
    private string _contact_address = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"contact_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string contact_address
    {
      get { return _contact_address; }
      set { _contact_address = value; }
    }
    private string _contact_postcode = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"contact_postcode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string contact_postcode
    {
      get { return _contact_postcode; }
      set { _contact_postcode = value; }
    }
    private string _fixed_line_phone = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"fixed_line_phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fixed_line_phone
    {
      get { return _fixed_line_phone; }
      set { _fixed_line_phone = value; }
    }
    private string _mobile_phone = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"mobile_phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mobile_phone
    {
      get { return _mobile_phone; }
      set { _mobile_phone = value; }
    }
    private string _email = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private string _source = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string source
    {
      get { return _source; }
      set { _source = value; }
    }
    private string _same_education = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"same_education", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string same_education
    {
      get { return _same_education; }
      set { _same_education = value; }
    }
    private string _school_code = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"school_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string school_code
    {
      get { return _school_code; }
      set { _school_code = value; }
    }
    private string _school_name = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"school_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string school_name
    {
      get { return _school_name; }
      set { _school_name = value; }
    }
    private string _major_name = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"major_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string major_name
    {
      get { return _major_name; }
      set { _major_name = value; }
    }
    private string _study_type = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"study_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string study_type
    {
      get { return _study_type; }
      set { _study_type = value; }
    }
    private string _last_education = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"last_education", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string last_education
    {
      get { return _last_education; }
      set { _last_education = value; }
    }
    private string _diploma_number = "";
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"diploma_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string diploma_number
    {
      get { return _diploma_number; }
      set { _diploma_number = value; }
    }
    private string _graduate_date = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"graduate_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string graduate_date
    {
      get { return _graduate_date; }
      set { _graduate_date = value; }
    }
    private string _register_number = "";
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"register_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string register_number
    {
      get { return _register_number; }
      set { _register_number = value; }
    }
    private string _last_degree = "";
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"last_degree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string last_degree
    {
      get { return _last_degree; }
      set { _last_degree = value; }
    }
    private string _graduate_number = "";
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"graduate_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string graduate_number
    {
      get { return _graduate_number; }
      set { _graduate_number = value; }
    }
    private string _adjust_major_code = "";
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"adjust_major_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string adjust_major_code
    {
      get { return _adjust_major_code; }
      set { _adjust_major_code = value; }
    }
    private string _adjust_major_name = "";
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"adjust_major_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string adjust_major_name
    {
      get { return _adjust_major_name; }
      set { _adjust_major_name = value; }
    }
    private string _apply_place_code = "";
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"apply_place_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_place_code
    {
      get { return _apply_place_code; }
      set { _apply_place_code = value; }
    }
    private string _apply_faculty = "";
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"apply_faculty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_faculty
    {
      get { return _apply_faculty; }
      set { _apply_faculty = value; }
    }
    private string _apply_faculty_name = "";
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"apply_faculty_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_faculty_name
    {
      get { return _apply_faculty_name; }
      set { _apply_faculty_name = value; }
    }
    private string _apply_major_code = "";
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"apply_major_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_major_code
    {
      get { return _apply_major_code; }
      set { _apply_major_code = value; }
    }
    private string _apply_major_name = "";
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"apply_major_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_major_name
    {
      get { return _apply_major_name; }
      set { _apply_major_name = value; }
    }
    private string _apply_work_direction = "";
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"apply_work_direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_work_direction
    {
      get { return _apply_work_direction; }
      set { _apply_work_direction = value; }
    }
    private string _apply_work_direction_name = "";
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"apply_work_direction_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_work_direction_name
    {
      get { return _apply_work_direction_name; }
      set { _apply_work_direction_name = value; }
    }
    private string _exam_type = "";
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"exam_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string exam_type
    {
      get { return _exam_type; }
      set { _exam_type = value; }
    }
    private string _special_plan = "";
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"special_plan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string special_plan
    {
      get { return _special_plan; }
      set { _special_plan = value; }
    }
    private string _apply_type = "";
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"apply_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apply_type
    {
      get { return _apply_type; }
      set { _apply_type = value; }
    }
    private string _orientation_train_place_code = "";
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"orientation_train_place_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orientation_train_place_code
    {
      get { return _orientation_train_place_code; }
      set { _orientation_train_place_code = value; }
    }
    private string _orientation_train_place = "";
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"orientation_train_place", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orientation_train_place
    {
      get { return _orientation_train_place; }
      set { _orientation_train_place = value; }
    }
    private string _standby_information = "";
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"standby_information", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string standby_information
    {
      get { return _standby_information; }
      set { _standby_information = value; }
    }
    private string _standby_information_one = "";
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"standby_information_one", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string standby_information_one
    {
      get { return _standby_information_one; }
      set { _standby_information_one = value; }
    }
    private string _standby_information_two = "";
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"standby_information_two", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string standby_information_two
    {
      get { return _standby_information_two; }
      set { _standby_information_two = value; }
    }
    private string _standby_information_three = "";
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"standby_information_three", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string standby_information_three
    {
      get { return _standby_information_three; }
      set { _standby_information_three = value; }
    }
    private string _political_code = "";
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"political_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string political_code
    {
      get { return _political_code; }
      set { _political_code = value; }
    }
    private string _political_name = "";
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"political_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string political_name
    {
      get { return _political_name; }
      set { _political_name = value; }
    }
    private string _foreign_code = "";
    [global::ProtoBuf.ProtoMember(63, IsRequired = false, Name=@"foreign_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string foreign_code
    {
      get { return _foreign_code; }
      set { _foreign_code = value; }
    }
    private string _foreign_name = "";
    [global::ProtoBuf.ProtoMember(64, IsRequired = false, Name=@"foreign_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string foreign_name
    {
      get { return _foreign_name; }
      set { _foreign_name = value; }
    }
    private string _business_one_code = "";
    [global::ProtoBuf.ProtoMember(65, IsRequired = false, Name=@"business_one_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string business_one_code
    {
      get { return _business_one_code; }
      set { _business_one_code = value; }
    }
    private string _business_one_name = "";
    [global::ProtoBuf.ProtoMember(66, IsRequired = false, Name=@"business_one_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string business_one_name
    {
      get { return _business_one_name; }
      set { _business_one_name = value; }
    }
    private string _business_two_code = "";
    [global::ProtoBuf.ProtoMember(67, IsRequired = false, Name=@"business_two_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string business_two_code
    {
      get { return _business_two_code; }
      set { _business_two_code = value; }
    }
    private string _business_two_name = "";
    [global::ProtoBuf.ProtoMember(68, IsRequired = false, Name=@"business_two_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string business_two_name
    {
      get { return _business_two_name; }
      set { _business_two_name = value; }
    }
    private uint _political_score = default(uint);
    [global::ProtoBuf.ProtoMember(69, IsRequired = false, Name=@"political_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint political_score
    {
      get { return _political_score; }
      set { _political_score = value; }
    }
    private uint _foreign_score = default(uint);
    [global::ProtoBuf.ProtoMember(70, IsRequired = false, Name=@"foreign_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint foreign_score
    {
      get { return _foreign_score; }
      set { _foreign_score = value; }
    }
    private uint _business_one_score = default(uint);
    [global::ProtoBuf.ProtoMember(71, IsRequired = false, Name=@"business_one_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint business_one_score
    {
      get { return _business_one_score; }
      set { _business_one_score = value; }
    }
    private uint _business_two_score = default(uint);
    [global::ProtoBuf.ProtoMember(72, IsRequired = false, Name=@"business_two_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint business_two_score
    {
      get { return _business_two_score; }
      set { _business_two_score = value; }
    }
    private uint _total_score = default(uint);
    [global::ProtoBuf.ProtoMember(73, IsRequired = false, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _volunteer_type = "";
    [global::ProtoBuf.ProtoMember(74, IsRequired = false, Name=@"volunteer_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string volunteer_type
    {
      get { return _volunteer_type; }
      set { _volunteer_type = value; }
    }
    private string _tutor = "";
    [global::ProtoBuf.ProtoMember(75, IsRequired = false, Name=@"tutor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tutor
    {
      get { return _tutor; }
      set { _tutor = value; }
    }
    private string _student_confirm_status = "";
    [global::ProtoBuf.ProtoMember(76, IsRequired = false, Name=@"student_confirm_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string student_confirm_status
    {
      get { return _student_confirm_status; }
      set { _student_confirm_status = value; }
    }
    private string _student_confirm_time = "";
    [global::ProtoBuf.ProtoMember(77, IsRequired = false, Name=@"student_confirm_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string student_confirm_time
    {
      get { return _student_confirm_time; }
      set { _student_confirm_time = value; }
    }
    private string _student_reexamine = "";
    [global::ProtoBuf.ProtoMember(78, IsRequired = false, Name=@"student_reexamine", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string student_reexamine
    {
      get { return _student_reexamine; }
      set { _student_reexamine = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Students")]
  public partial class Students : global::ProtoBuf.IExtensible
  {
    public Students() {}
    
    private readonly global::System.Collections.Generic.List<message.StudentInfo> _student = new global::System.Collections.Generic.List<message.StudentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"student", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<message.StudentInfo> student
    {
      get { return _student; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}